drop table CRAWLER CASCADE CONSTRAINTS;
--테스트 테이블
create table CRAWLER(
   CRAWLER_NUM	NUMBER       NOT NULL,   	--글번호
   CRAWLER_IMAGE VARCHAR2(2000) NOT NULL,			--이미지
   CRAWLER_COVER_SUBJECT	VARCHAR2(500)  NOT NULL, --제목
   CRAWLER_SUMMARY	VARCHAR2(2000) NOT NULL,		--내용
   CRAWLER_DATE	VARCHAR2(200) NOT NULL,				--날짜
   CRAWLER_LINK VARCHAR2(2000),						--링크
	PRIMARY KEY(CRAWLER_NUM)
);
select * from CRAWLER


